# Natural Language Processing (NLP) with spaCy

## Topics
1. Part-of-Speech (POS) Tagging
2. Named Entity Recognition (NER)
3. Dependency Parsing

### Objective
The objective of this notebook is to understand how spaCy processes text and extracts useful linguistic information such as grammatical roles, named entities, and syntactic relationships between words.

# Introduction to spaCy

spaCy is an open-source Natural Language Processing (NLP) library in Python.

It provides many useful NLP features such as:

- Tokenization
- Part-of-Speech (POS) Tagging
- Named Entity Recognition (NER)
- Dependency Parsing
- Text Classification
- Lemmatization

In this notebook, I will focus on:

1. POS Tagging
2. Named Entity Recognition (NER)
3. Dependency Parsing

In [4]:
# Install spaCy

!pip install spacy

Requirement already satisfied: spacy in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (3.8.14)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from spacy) (0.26.7)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from spacy) (2.4.6)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from spacy) (2.34.2)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from spacy) (2.13.4)
Requirement already satisfied: jinja2 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from spacy) (65.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from spacy) (26.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.17)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.5.20)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: colorama in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.24.0)
Requirement already satisfied: smart-open>=5.2.1 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (7.6.1)
Requirement already satisfied: httpx>=0.24.0 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: anyio in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.13.0)
Requirement already satisfied: httpcore==1.* in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Requirement already satisfied: wrapt in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.2.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\lenevo\appdata\local\programs\python\python311\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: C:\Users\lenevo\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip

In [2]:
# downloading english model for spaCy

!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     --- ------------------------------------ 1.0/12.8 MB 6.5 MB/s eta 0:00:02
     ------------- -------------------------- 4.5/12.8 MB 12.8 MB/s eta 0:00:01
     ------------------------------ --------- 9.7/12.8 MB 17.8 MB/s eta 0:00:01
     --------------------------------------  12.6/12.8 MB 20.2 MB/s eta 0:00:01
     --------------------------------------  12.6/12.8 MB 20.2 MB/s eta 0:00:01
     --------------------------------------  12.6/12.8 MB 20.2 MB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 9.6 MB/s  0:00:01
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
# Importing spaCy and loading the English model

import spacy

nlp = spacy.load("en_core_web_sm")

# Creating a Sample Document

A document is created by passing text into the spaCy language model.

The model processes the text and stores linguistic information that can be accessed later.

In [11]:
text = "NLP is a fascinating field. It allows us to understand and process human language. I am excited to learn more about it!"

doc = nlp(text)

print(doc)

NLP is a fascinating field. It allows us to understand and process human language. I am excited to learn more about it!

# Tokenization

Tokenization is the process of breaking text into smaller units called tokens.

In [12]:
for token in doc:
    print(token.text)

NLP
is
a
fascinating
field
.
It
allows
us
to
understand
and
process
human
language
.
I
am
excited
to
learn
more
about
it
!

# Part-of-Speech (POS) Tagging

POS Tagging identifies the grammatical role of each word in a sentence.

Examples:

- Noun
- Verb
- Adjective
- Pronoun
- Adverb
- Determiner

This helps computers understand sentence structure.

In [13]:
for token in doc:
    print(token.text, "-------->", token.pos_)

NLP --------> PROPN
is --------> AUX
a --------> DET
fascinating --------> ADJ
field --------> NOUN
. --------> PUNCT
It --------> PRON
allows --------> VERB
us --------> PRON
to --------> PART
understand --------> VERB
and --------> CCONJ
process --------> VERB
human --------> ADJ
language --------> NOUN
. --------> PUNCT
I --------> PRON
am --------> AUX
excited --------> ADJ
to --------> PART
learn --------> VERB
more --------> ADJ
about --------> ADP
it --------> PRON
! --------> PUNCT

# Detailed POS Information

spaCy provides:

- token.text : actual word
- token.pos_ : general POS tag
- token.tag_ : detailed POS tag

In [14]:
for token in doc:
    print(
        f"Word: {token.text:15}",
        f"POS: {token.pos_:10}",
        f"Detailed Tag: {token.tag_}",
    )

Word: NLP             POS: PROPN      Detailed Tag: NNP
Word: is              POS: AUX        Detailed Tag: VBZ
Word: a               POS: DET        Detailed Tag: DT
Word: fascinating     POS: ADJ        Detailed Tag: JJ
Word: field           POS: NOUN       Detailed Tag: NN
Word: .               POS: PUNCT      Detailed Tag: .
Word: It              POS: PRON       Detailed Tag: PRP
Word: allows          POS: VERB       Detailed Tag: VBZ
Word: us              POS: PRON       Detailed Tag: PRP
Word: to              POS: PART       Detailed Tag: TO
Word: understand      POS: VERB       Detailed Tag: VB
Word: and             POS: CCONJ      Detailed Tag: CC
Word: process         POS: VERB       Detailed Tag: VB
Word: human           POS: ADJ        Detailed Tag: JJ
Word: language        POS: NOUN       Detailed Tag: NN
Word: .               POS: PUNCT      Detailed Tag: .
Word: I               POS: PRON       Detailed Tag: PRP
Word: am              POS: AUX        Detailed Tag: VBP
Word: excited         POS: ADJ        Detailed Tag: JJ
Word: to              POS: PART       Detailed Tag: TO
Word: learn           POS: VERB       Detailed Tag: VB
Word: more            POS: ADJ        Detailed Tag: JJR
Word: about           POS: ADP        Detailed Tag: IN
Word: it              POS: PRON       Detailed Tag: PRP
Word: !               POS: PUNCT      Detailed Tag: .

In [15]:
# POS as Table

import pandas as pd

data = []

for token in doc:
    data.append([
        token.text,
        token.pos_,
        token.tag_
    ])

df = pd.DataFrame(
    data,
    columns=["Word", "POS", "Detailed Tag"]
)

df

           Word    POS Detailed Tag
0           NLP  PROPN          NNP
1            is    AUX          VBZ
2             a    DET           DT
3   fascinating    ADJ           JJ
4         field   NOUN           NN
5             .  PUNCT            .
6            It   PRON          PRP
7        allows   VERB          VBZ
8            us   PRON          PRP
9            to   PART           TO
10   understand   VERB           VB
11          and  CCONJ           CC
12      process   VERB           VB
13        human    ADJ           JJ
14     language   NOUN           NN
15            .  PUNCT            .
16            I   PRON          PRP
17           am    AUX          VBP
18      excited    ADJ           JJ
19           to   PART           TO
20        learn   VERB           VB
21         more    ADJ          JJR
22        about    ADP           IN
23           it   PRON          PRP
24            !  PUNCT            .

# Named Entity Recognition (NER)

Named Entity Recognition identifies important real-world entities.

Examples:

PERSON:
- Elon Musk
- Lionel Messi

ORG:
- Google
- Microsoft

GPE:
- Nepal
- London

DATE:
- January 2025

NER helps in information extraction from text.

In [24]:
text = """
Microsoft hired Jonas  in New York on Monday.
"""

doc = nlp(text)

for ent in doc.ents:
    print(ent.text, "---->", ent.label_)

Microsoft ----> ORG
Jonas ----> PERSON
New York ----> GPE
Monday ----> DATE

# Displaying Entities in Table Format

In [25]:
entity_data = []

for ent in doc.ents:
    entity_data.append([
        ent.text,
        ent.label_
    ])

entity_df = pd.DataFrame(
    entity_data,
    columns=["Entity", "Label"]
)

entity_df

      Entity   Label
0  Microsoft     ORG
1      Jonas  PERSON
2   New York     GPE
3     Monday    DATE

### Visualizing NER

In [26]:
from spacy import displacy

displacy.render(doc,style="ent", jupyter=True)

# Dependency Parsing

Dependency Parsing identifies relationships between words.

It answers questions such as:

- Who performed the action?
- What was the action?
- What received the action?

Example:

"The cat chased the mouse."

Subject:
cat

Verb:
chased

Object:
mouse

In [27]:
text = "The cat chased the mouse."

doc = nlp(text)

for token in doc:
    print(
        token.text,
        token.dep_,
        token.head.text
    )

The det cat
cat nsubj chased
chased ROOT chased
the det mouse
mouse dobj chased
. punct chased

# Understanding Dependency Relationships

In [28]:
dependency_data = []

for token in doc:
    dependency_data.append([
        token.text,
        token.dep_,
        token.head.text
    ])

dependency_df = pd.DataFrame(
    dependency_data,
    columns=["Word", "Dependency", "Head Word"]
)

dependency_df

     Word Dependency Head Word
0     The        det       cat
1     cat      nsubj    chased
2  chased       ROOT    chased
3     the        det     mouse
4   mouse       dobj    chased
5       .      punct    chased

### Dependency visualization

In [29]:
displacy.render(doc, style="dep", jupyter=True)

# Combined Example

Now we will apply POS Tagging, NER, and Dependency Parsing on a single sentence.

In [30]:
text = """
Google CEO Sundar Pichai visited London in June 2025.
"""

doc = nlp(text)

print("Sentence:")
print(text)

Sentence:

Google CEO Sundar Pichai visited London in June 2025.

In [31]:
print("POS TAGGING")

for token in doc:
    print(token.text, token.pos_)

POS TAGGING

 SPACE
Google PROPN
CEO PROPN
Sundar PROPN
Pichai PROPN
visited VERB
London PROPN
in ADP
June PROPN
2025 NUM
. PUNCT

 SPACE

In [32]:
print("NAMED ENTITIES")

for ent in doc.ents:
    print(ent.text, ent.label_)

NAMED ENTITIES
Google ORG
Sundar Pichai PERSON
London GPE
June 2025 DATE

In [33]:
print("DEPENDENCY PARSING")

for token in doc:
    print(
        token.text,
        token.dep_,
        token.head.text
    )

DEPENDENCY PARSING

 dep CEO
Google compound CEO
CEO compound Pichai
Sundar compound Pichai
Pichai nsubj visited
visited ROOT visited
London dobj visited
in prep visited
June pobj in
2025 nummod June
. punct visited

 dep .

## complete analysis table

In [34]:
analysis = []

for token in doc:
    analysis.append([
        token.text,
        token.pos_,
        token.dep_,
        token.head.text
    ])

analysis_df = pd.DataFrame(
    analysis,
    columns=[
        "Word",
        "POS",
        "Dependency",
        "Head Word"
    ]
)

analysis_df

       Word    POS Dependency Head Word
0        \n  SPACE        dep       CEO
1    Google  PROPN   compound       CEO
2       CEO  PROPN   compound    Pichai
3    Sundar  PROPN   compound    Pichai
4    Pichai  PROPN      nsubj   visited
5   visited   VERB       ROOT   visited
6    London  PROPN       dobj   visited
7        in    ADP       prep   visited
8      June  PROPN       pobj        in
9      2025    NUM     nummod      June
10        .  PUNCT      punct   visited
11       \n  SPACE        dep         .

# NLP Workflow Used in This Notebook

Text
↓
Tokenization
↓
POS Tagging
↓
Named Entity Recognition
↓
Dependency Parsing
↓
Information Extraction

Explanation:

1. Text is given to spaCy.
2. spaCy breaks text into tokens.
3. POS Tagging identifies grammatical roles.
4. NER identifies important entities.
5. Dependency Parsing identifies relationships among words.
6. Extracted information can be used for downstream NLP applications.

# Conclusion

In this notebook, we learned:

1. How spaCy processes text.
2. How to perform POS Tagging.
3. How to identify named entities using NER.
4. How to understand sentence structure using Dependency Parsing.

These techniques form the foundation of many NLP applications such as:

- Chatbots
- Search Engines
- Resume Parsing
- Information Extraction
- Text Analytics
- Question Answering Systems